### ISSUE TITLE
That's not the good place but

### ISSUE THREAD

**Issue by Popolon** [k2s/dockerfiles#1]
I'm sorry to write this here, but as there is no contact email, there are some change asked on the package you manage on archlinux, pacaur, and as you probably didn't provide email, you are not noitified of this reports. This is really blocking for lot of users. "wxlua-svn 252-1". Do you still maintain it, and then could you then apply the proposed patchs please ? Or do you let your package orphelin, so another people can continue to maintain them.

Again really sorry to fill this request here.

Best regards.

**Comment by k2s** [comment]
Hi,
I was not looking for the package because there is a co-maintainer who packaged the last version.
There is regular process to request disowning of AUR package described here https://wiki.archlinux.org/index.php/Arch_User_Repository.
I disowned the package becasue I am not directly interested in it anymore.

Best regards.
